Repository OCA/ddmrp, pull requests merged in 2020-07, with the labels that each got.

#50 [13.0][IMP] ddmrp: add dedicated settings and `ddmrp_auto_update_nfp` option.
  ddmrp/__manifest__.py
  ddmrp/models/__init__.py
  ddmrp/models/product_product.py
  ddmrp/models/res_company.py
  ddmrp/models/stock_buffer.py
  ddmrp/models/stock_location.py
  ddmrp/models/stock_move.py
  ddmrp/readme/newsfragments/50.feature
  ddmrp/static/description/icon.png
  ddmrp/tests/test_ddmrp.py
  ddmrp/wizards/__init__.py
  ddmrp/wizards/res_config_settings.py
  ddmrp/wizards/res_config_settings_views.xml
  ddmrp_history/models/stock_buffer.py
Labels: approved, bot is merging ⏳

#51 [13.0][MIG] ddmrp_adjustment
  ddmrp/wizards/res_config_settings.py
  ddmrp/wizards/res_config_settings_views.xml
  ddmrp_adjustment/README.rst
  ddmrp_adjustment/__init__.py
  ddmrp_adjustment/__manifest__.py
  ddmrp_adjustment/models/__init__.py
  ddmrp_adjustment/models/ddmrp_adjustment.py
  ddmrp_adjustment/models/ddmrp_adjustment_demand.py
  ddmrp_adjustment/models/stock_buffer.py
  ddmrp_adjustment/readme/CONTRIBUTORS.rst
  ddmrp_adjustment/readme/DESCRIPTION.rst
  ddmrp_adjustment/readme/HISTORY.rst
  ddmrp_adjustment/readme/ROADMAP.rst
  ddmrp_adjustment/readme/USAGE.rst
  ddmrp_adjustment/security/ddmrp_security.xml
  ddmrp_adjustment/security/ir.model.access.csv
  ddmrp_adjustment/static/description/icon.png
  ddmrp_adjustment/static/description/index.html
  ddmrp_adjustment/tests/__init__.py
  ddmrp_adjustment/tests/test_adjustment_wizard.py
  ddmrp_adjustment/tests/test_adu_dlt_adjustment.py
  ddmrp_adjustment/tests/test_common.py
  ddmrp_adjustment/views/ddmrp_adjustment_demand_view.xml
  ddmrp_adjustment/views/ddmrp_adjustment_view.xml
  ddmrp_adjustment/views/stock_buffer_view.xml
  ddmrp_adjustment/wizards/__init__.py
  ddmrp_adjustment/wizards/ddmrp_adjustment_sheet.py
  ddmrp_adjustment/wizards/ddmrp_adjustment_wizard_view.xml
  setup/ddmrp_adjustment/odoo/addons/ddmrp_adjustment
  setup/ddmrp_adjustment/setup.py
Labels: approved, bot is merging ⏳

#54 [13.0][ADD] ddmrp_coverage_days
  ddmrp_coverage_days/README.rst
  ddmrp_coverage_days/__init__.py
  ddmrp_coverage_days/__manifest__.py
  ddmrp_coverage_days/models/__init__.py
  ddmrp_coverage_days/models/stock_buffer.py
  ddmrp_coverage_days/readme/CONTRIBUTORS.rst
  ddmrp_coverage_days/readme/DESCRIPTION.rst
  ddmrp_coverage_days/readme/HISTORY.rst
  ddmrp_coverage_days/static/description/icon.png
  ddmrp_coverage_days/static/description/index.html
  ddmrp_coverage_days/tests/__init__.py
  ddmrp_coverage_days/tests/test_ddmrp_coverage_days.py
  ddmrp_coverage_days/views/stock_buffer_views.xml
  setup/ddmrp_coverage_days/odoo/addons/ddmrp_coverage_days
  setup/ddmrp_coverage_days/setup.py
Labels: approved, bot is merging ⏳

#53 [13.0][ADD] ddmrp_packaging
  ddmrp_packaging/README.rst
  ddmrp_packaging/__init__.py
  ddmrp_packaging/__manifest__.py
  ddmrp_packaging/models/__init__.py
  ddmrp_packaging/models/stock_buffer.py
  ddmrp_packaging/readme/CONTRIBUTORS.rst
  ddmrp_packaging/readme/DESCRIPTION.rst
  ddmrp_packaging/readme/HISTORY.rst
  ddmrp_packaging/readme/INSTALL.rst
  ddmrp_packaging/static/description/icon.png
  ddmrp_packaging/static/description/index.html
  ddmrp_packaging/views/stock_buffer_view.xml
  setup/ddmrp_packaging/odoo/addons/ddmrp_packaging
  setup/ddmrp_packaging/setup.py
Labels: approved, bot is merging ⏳

#55 [13.0][ADD] stock_buffer_capacity_limit
  ddmrp/wizards/res_config_settings.py
  ddmrp/wizards/res_config_settings_views.xml
  setup/stock_buffer_capacity_limit/odoo/addons/stock_buffer_capacity_limit
  setup/stock_buffer_capacity_limit/setup.py
  stock_buffer_capacity_limit/README.rst
  stock_buffer_capacity_limit/__init__.py
  stock_buffer_capacity_limit/__manifest__.py
  stock_buffer_capacity_limit/models/__init__.py
  stock_buffer_capacity_limit/models/stock_buffer.py
  stock_buffer_capacity_limit/readme/CONTRIBUTORS.rst
  stock_buffer_capacity_limit/readme/DESCRIPTION.rst
  stock_buffer_capacity_limit/readme/HISTORY.rst
  stock_buffer_capacity_limit/static/description/icon.png
  stock_buffer_capacity_limit/static/description/index.html
  stock_buffer_capacity_limit/tests/__init__.py
  stock_buffer_capacity_limit/tests/test_stock_buffer_capacity_limit.py
  stock_buffer_capacity_limit/views/stock_buffer_view.xml
Labels: approved, bot is merging ⏳

#56 [13.0][IMP] ddmrp_packaging: add package_multiple field.
  ddmrp_packaging/models/stock_buffer.py
  ddmrp_packaging/views/stock_buffer_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#52 [13.0] Add stock_buffer_route
  setup/stock_buffer_route/odoo/addons/stock_buffer_route
  setup/stock_buffer_route/setup.py
  stock_buffer_route/__init__.py
  stock_buffer_route/__manifest__.py
  stock_buffer_route/models/__init__.py
  stock_buffer_route/models/stock_buffer.py
  stock_buffer_route/readme/CONTRIBUTORS.rst
  stock_buffer_route/readme/DESCRIPTION.rst
  stock_buffer_route/readme/USAGE.rst
  stock_buffer_route/static/description/icon.png
  stock_buffer_route/tests/__init__.py
  stock_buffer_route/tests/test_stock_buffer_route.py
  stock_buffer_route/views/stock_buffer_views.xml
Labels: bot is merging ⏳

#57 stock_buffer_route: Allow selecting buy/manufacture routes in buffers
  stock_buffer_route/models/stock_buffer.py
Labels: approved, bot is merging ⏳, ready to merge
