Repository OCA/ddmrp, pull requests merged in 2020-10, with the labels that each got.

#76 [13.0] Fix computation for buffer route domain
  stock_buffer_route/models/stock_buffer.py
Labels: approved, bot is merging ⏳, bug, needs review, ready to merge

#79 [13.0][UPD] Eficent -> ForgeFlow
  stock_buffer_route/__manifest__.py
  stock_buffer_route/readme/CONTRIBUTORS.rst
Labels: approved, bot is merging ⏳

#78 [13.0][IMP] ddmrp: show a warning icon when a buffer has long term supply
  ddmrp/models/purchase_order.py
  ddmrp/models/stock_buffer.py
  ddmrp/tests/common.py
  ddmrp/tests/test_ddmrp.py
  ddmrp/views/stock_buffer_view.xml
Labels: approved, bot is merging ⏳, ready to merge, work in progress
