Repository OCA/ddmrp, pull requests merged in 2021-12, with the labels that each got.

#67 [13.0][FIX] ddmrp: error when adding a purchase order line
  ddmrp/models/stock_buffer.py
Labels: approved, bot is merging ⏳, stale

#183 [14.0][FW] [13.0][FIX] ddmrp_product_replace: compute incoming qty
  ddmrp_product_replace/models/stock_buffer.py
  ddmrp_product_replace/tests/test_product_replace.py
Labels: bot is merging ⏳

#182 [13.0][FIX] ddmrp_product_replace: compute incoming qty
  ddmrp_product_replace/models/stock_buffer.py
  ddmrp_product_replace/tests/test_product_replace.py
Labels: approved, bot is merging ⏳

#179 [14.0][FW] ddmrp: multiple ports from 13.0
  ddmrp/__manifest__.py
  ddmrp/models/__init__.py
  ddmrp/models/stock_buffer.py
  ddmrp/models/stock_picking.py
  ddmrp/tests/test_ddmrp.py
  ddmrp/views/stock_buffer_view.xml
  ddmrp/views/stock_picking.xml
Labels: approved, bot is merging ⏳

#184 [14.0][FIX] ddmrp: Fix error when adding a purchase order line
  ddmrp/models/stock_buffer.py
Labels: bot is merging ⏳
