Repository OCA/ddmrp, pull requests merged in 2021-09, with the labels that each got.

#150 [13.0][IMP] Add yearly consumption button stock.buffer
  ddmrp/models/stock_buffer.py
  ddmrp/views/stock_buffer_view.xml
  ddmrp/views/stock_move_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#160 [13.0][IMP] Ease filtering and usage of buffer tree view
  ddmrp/views/stock_buffer_view.xml
  ddmrp_coverage_days/views/stock_buffer_views.xml
  stock_buffer_route/views/stock_buffer_views.xml
Labels: bot is merging ⏳

#164 [14.0][ADD] Packaging to make procurement wizard
  ddmrp_packaging/__init__.py
  ddmrp_packaging/__manifest__.py
  ddmrp_packaging/wizards/__init__.py
  ddmrp_packaging/wizards/make_procurement_buffer.py
  ddmrp_packaging/wizards/make_procurement_buffer_view.xml
Labels: bot is merging ⏳

#165 [14.0][IMP] ddmrp: Ease filtering and usage of buffer tree view
  ddmrp/views/stock_buffer_view.xml
  ddmrp_coverage_days/views/stock_buffer_views.xml
  stock_buffer_route/views/stock_buffer_views.xml
Labels: bot is merging ⏳

#163 [13.0][FIX] ddmrp: reuse `_past_moves_domain` in yearly consuption action
  ddmrp/models/stock_buffer.py
Labels: bot is merging ⏳

#166 [14.0][IMP] ddmrp: Add yearly consumption button stock.buffer
  ddmrp/models/stock_buffer.py
  ddmrp/tests/test_ddmrp.py
  ddmrp/views/stock_buffer_view.xml
  ddmrp/views/stock_move_views.xml
Labels: bot is merging ⏳

#167 [14.0][MIG] ddmrp_exclude_moves_adu_calc: Migrate to 14.0
  ddmrp_exclude_moves_adu_calc/README.rst
  ddmrp_exclude_moves_adu_calc/__init__.py
  ddmrp_exclude_moves_adu_calc/__manifest__.py
  ddmrp_exclude_moves_adu_calc/i18n/ddmrp_exclude_moves_adu_calc.pot
  ddmrp_exclude_moves_adu_calc/i18n/fr.po
  ddmrp_exclude_moves_adu_calc/models/__init__.py
  ddmrp_exclude_moves_adu_calc/models/stock_buffer.py
  ddmrp_exclude_moves_adu_calc/models/stock_location.py
  ddmrp_exclude_moves_adu_calc/models/stock_move.py
  ddmrp_exclude_moves_adu_calc/readme/CONTRIBUTORS.rst
  ddmrp_exclude_moves_adu_calc/readme/CREDITS.rst
  ddmrp_exclude_moves_adu_calc/readme/DESCRIPTION.rst
  ddmrp_exclude_moves_adu_calc/readme/HISTORY.rst
  ddmrp_exclude_moves_adu_calc/readme/USAGE.rst
  ddmrp_exclude_moves_adu_calc/static/description/icon.png
  ddmrp_exclude_moves_adu_calc/static/description/index.html
  ddmrp_exclude_moves_adu_calc/tests/__init__.py
  ddmrp_exclude_moves_adu_calc/tests/test_ddmrp.py
  ddmrp_exclude_moves_adu_calc/views/stock_location_view.xml
  ddmrp_exclude_moves_adu_calc/views/stock_move_view.xml
  setup/ddmrp_exclude_moves_adu_calc/odoo/addons/ddmrp_exclude_moves_adu_calc
  setup/ddmrp_exclude_moves_adu_calc/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#174 [14.0][MIG] ddmrp_warning
  ddmrp_warning/README.rst
  ddmrp_warning/__init__.py
  ddmrp_warning/__manifest__.py
  ddmrp_warning/data/ddmrp_warning_definition_data.xml
  ddmrp_warning/data/ir_cron.xml
  ddmrp_warning/i18n/ddmrp_warning.pot
  ddmrp_warning/models/__init__.py
  ddmrp_warning/models/ddmrp_warning_definition.py
  ddmrp_warning/models/ddmrp_warning_item.py
  ddmrp_warning/models/stock_buffer.py
  ddmrp_warning/readme/CONTRIBUTORS.rst
  ddmrp_warning/readme/DESCRIPTION.rst
  ddmrp_warning/readme/USAGE.rst
  ddmrp_warning/security/ir.model.access.csv
  ddmrp_warning/static/description/icon.png
  ddmrp_warning/static/description/index.html
  ddmrp_warning/tests/__init__.py
  ddmrp_warning/tests/test_ddmrp_warning.py
  ddmrp_warning/views/ddmrp_buffer_view.xml
  ddmrp_warning/views/ddmrp_warning_definition_views.xml
  ddmrp_warning/views/ddmrp_warning_item_views.xml
  setup/ddmrp_warning/odoo/addons/ddmrp_warning
  setup/ddmrp_warning/setup.py
Labels: approved, bot is merging ⏳
