Repository OCA/ddmrp, pull requests merged in 2021-04, with the labels that each got.

#112 [13.0][IMP] ddmrp: add ddmrp_qty_multiple_tolerance option.
  ddmrp/models/res_company.py
  ddmrp/models/stock_buffer.py
  ddmrp/tests/common.py
  ddmrp/tests/test_ddmrp.py
  ddmrp/wizards/res_config_settings.py
  ddmrp/wizards/res_config_settings_views.xml
Labels: bot is merging ⏳

#116 [13.0] Fix console warnings due to list view renderer
  ddmrp/static/src/js/list_renderer_buffer_info.js
Labels: approved, bot is merging ⏳

#118 [14.0][IMP] ddmrp: add ddmrp_qty_multiple_tolerance option.
  ddmrp/models/res_company.py
  ddmrp/models/stock_buffer.py
  ddmrp/tests/common.py
  ddmrp/tests/test_ddmrp.py
  ddmrp/wizards/res_config_settings.py
  ddmrp/wizards/res_config_settings_views.xml
Labels: bot is merging ⏳

#119 [14.0] ddmrp: Fix console warnings due to list view renderer
  ddmrp/static/src/js/list_renderer_buffer_info.js
Labels: approved, bot is merging ⏳

#115 [13.0][FIX] ddmrp_packaging compute qty_multiple
  ddmrp_packaging/models/stock_buffer.py
Labels: approved, bot is merging ⏳, ready to merge

#94 [13.0] Add reschedule procurement on distributed buffers
  ddmrp/models/stock_buffer.py
  ddmrp/models/stock_buffer_profile.py
  ddmrp/tests/__init__.py
  ddmrp/tests/test_distributed_max_proc_time.py
  ddmrp/views/stock_buffer_profile_view.xml
  ddmrp/wizards/make_procurement_buffer.py
  test-requirements.txt
Labels: approved, bot is merging ⏳, ready to merge

#61 [13.0][ddmrp] add method refresh_button in stock.buffer to be called from the buffer views instead of cron_actions
  ddmrp/models/stock_buffer.py
  ddmrp/views/stock_buffer_view.xml
Labels: bot is merging ⏳

#88 [13.0][ADD] ddmrp, smart button from picking to buffer
  ddmrp/__manifest__.py
  ddmrp/models/__init__.py
  ddmrp/models/stock_picking.py
  ddmrp/views/stock_picking.xml
Labels: approved, bot is merging ⏳, ready to merge

#108 [13.0][IMP] ddmrp_warning add applicable domain
  ddmrp_warning/models/ddmrp_warning_definition.py
  ddmrp_warning/models/stock_buffer.py
  ddmrp_warning/views/ddmrp_warning_definition_views.xml
Labels: bot is merging ⏳

#120 [13.0][FIX] ddmrp: do not show distributed_reschedule_max_proc_time in profile name if not in use.
  ddmrp/models/stock_buffer_profile.py
Labels: bot is merging ⏳

#121 [14.0] Add reschedule procurement on distributed buffers
  ddmrp/models/stock_buffer.py
  ddmrp/models/stock_buffer_profile.py
  ddmrp/tests/__init__.py
  ddmrp/tests/test_distributed_max_proc_time.py
  ddmrp/views/stock_buffer_profile_view.xml
  ddmrp/wizards/make_procurement_buffer.py
  test-requirements.txt
Labels: bot is merging ⏳

#122 [13.0][FIX] main supplier compute
  ddmrp/models/stock_buffer.py
Labels: approved, bot is merging ⏳, needs fixing, ready to merge

#123 [14.0][FIX] ddmrp: main supplier compute
  ddmrp/models/stock_buffer.py
Labels: bot is merging ⏳

#124 [13.0][FIX] ddmrp: since date planned is now a datetime, the limit for incoming should also be
  ddmrp/models/stock_buffer.py
  ddmrp/tests/common.py
  ddmrp/tests/test_distributed_max_proc_time.py
Labels: approved, bot is merging ⏳

#125 [13.0][FIX] ddmrp: extra lead time should only affect sizing.
  ddmrp/models/stock_buffer.py
  ddmrp/tests/test_ddmrp.py
Labels: approved, bot is merging ⏳

#126 [14.0][FIX] ddmrp: since date planned is now a datetime, the limit to
  ddmrp/models/stock_buffer.py
  ddmrp/tests/common.py
  ddmrp/tests/test_distributed_max_proc_time.py
Labels: bot is merging ⏳

#127 [14.0][FIX] ddmrp: extra lead time should only affect sizing.
  ddmrp/models/stock_buffer.py
  ddmrp/tests/test_ddmrp.py
Labels: bot is merging ⏳

#104 [13.0][IMP] ddmrp_sale: able to exclude sale order lines form ADU.
  ddmrp_sale/__manifest__.py
  ddmrp_sale/models/__init__.py
  ddmrp_sale/models/sale_order_line.py
  ddmrp_sale/views/sale_order_view.xml
Labels: approved, bot is merging ⏳, needs review, ready to merge

#130 [14.0] ddmrp: Fix security on make procurement on stock buffer
  ddmrp/wizards/make_procurement_buffer.py
Labels: bot is merging ⏳

#117 [13.0][REF] ddmrp_product_replace: add replace "modes".
  ddmrp_product_replace/__manifest__.py
  ddmrp_product_replace/models/stock_buffer.py
  ddmrp_product_replace/readme/USAGE.rst
  ddmrp_product_replace/tests/test_product_replace.py
  ddmrp_product_replace/views/stock_buffer_view.xml
  ddmrp_product_replace/wizards/__init__.py
  ddmrp_product_replace/wizards/ddmrp_product_replace.py
  ddmrp_product_replace/wizards/ddmrp_product_replace_view.xml
  ddmrp_product_replace/wizards/make_procurement_buffer.py
  ddmrp_product_replace/wizards/make_procurement_buffer_view.xml
Labels: bot is merging ⏳

#132 [14.0][UPD] ddmrp: adapt chart to new bokeh version 2.3.1.
  ddmrp/models/stock_buffer.py
Labels: bot is merging ⏳

#131 [14.0][MIG] ddmrp_history
  ddmrp_history/README.rst
  ddmrp_history/__init__.py
  ddmrp_history/__manifest__.py
  ddmrp_history/demo/ddmrp.history.csv
  ddmrp_history/i18n/ddmrp_history.pot
  ddmrp_history/i18n/es.po
  ddmrp_history/i18n/fr.po
  ddmrp_history/models/__init__.py
  ddmrp_history/models/ddmrp_history.py
  ddmrp_history/models/stock_buffer.py
  ddmrp_history/readme/CONTRIBUTORS.rst
  ddmrp_history/readme/CREDITS.rst
  ddmrp_history/readme/DESCRIPTION.rst
  ddmrp_history/readme/HISTORY.rst
  ddmrp_history/readme/INSTALL.rst
  ddmrp_history/readme/USAGE.rst
  ddmrp_history/security/ir.model.access.csv
  ddmrp_history/static/description/icon.png
  ddmrp_history/static/description/index.html
  ddmrp_history/tests/__init__.py
  ddmrp_history/tests/test_ddmrp_history.py
  ddmrp_history/views/ddmrp_history_view.xml
  ddmrp_history/views/stock_buffer_view.xml
  requirements.txt
  setup/ddmrp_history/odoo/addons/ddmrp_history
  setup/ddmrp_history/setup.py
Labels: bot is merging ⏳
