Repository OCA/ddmrp, pull requests merged in 2021-03, with the labels that each got.

#102 [13.0][MIG] ddmrp_exclude_moves_adu_calc
  ddmrp_exclude_moves_adu_calc/README.rst
  ddmrp_exclude_moves_adu_calc/__init__.py
  ddmrp_exclude_moves_adu_calc/__manifest__.py
  ddmrp_exclude_moves_adu_calc/i18n/fr.po
  ddmrp_exclude_moves_adu_calc/models/__init__.py
  ddmrp_exclude_moves_adu_calc/models/stock_buffer.py
  ddmrp_exclude_moves_adu_calc/models/stock_location.py
  ddmrp_exclude_moves_adu_calc/models/stock_move.py
  ddmrp_exclude_moves_adu_calc/readme/CONTRIBUTORS.rst
  ddmrp_exclude_moves_adu_calc/readme/DESCRIPTION.rst
  ddmrp_exclude_moves_adu_calc/readme/HISTORY.rst
  ddmrp_exclude_moves_adu_calc/readme/USAGE.rst
  ddmrp_exclude_moves_adu_calc/static/description/icon.png
  ddmrp_exclude_moves_adu_calc/static/description/index.html
  ddmrp_exclude_moves_adu_calc/tests/__init__.py
  ddmrp_exclude_moves_adu_calc/tests/test_ddmrp.py
  ddmrp_exclude_moves_adu_calc/views/stock_location_view.xml
  ddmrp_exclude_moves_adu_calc/views/stock_move_view.xml
  setup/ddmrp_exclude_moves_adu_calc/odoo/addons/ddmrp_exclude_moves_adu_calc
  setup/ddmrp_exclude_moves_adu_calc/setup.py
Labels: bot is merging ⏳

#103 [13.0][MIG] ddmrp_product_replace
  ddmrp_product_replace/README.rst
  ddmrp_product_replace/__init__.py
  ddmrp_product_replace/__manifest__.py
  ddmrp_product_replace/models/__init__.py
  ddmrp_product_replace/models/stock_buffer.py
  ddmrp_product_replace/readme/CONTRIBUTORS.rst
  ddmrp_product_replace/readme/CREDITS.rst
  ddmrp_product_replace/readme/DESCRIPTION.rst
  ddmrp_product_replace/readme/ROADMAP.rst
  ddmrp_product_replace/readme/USAGE.rst
  ddmrp_product_replace/static/description/icon.png
  ddmrp_product_replace/static/description/index.html
  ddmrp_product_replace/tests/__init__.py
  ddmrp_product_replace/tests/test_product_replace.py
  ddmrp_product_replace/views/stock_buffer_view.xml
  ddmrp_product_replace/wizards/__init__.py
  ddmrp_product_replace/wizards/ddmrp_product_replace.py
  ddmrp_product_replace/wizards/ddmrp_product_replace_view.xml
  setup/ddmrp_product_replace/odoo/addons/ddmrp_product_replace
  setup/ddmrp_product_replace/setup.py
Labels: approved, bot is merging ⏳, needs review, ready to merge

#107 [13.0][FIX] ddmrp: main supplier recomputed without respecting the sequence
  ddmrp/models/stock_buffer.py
Labels: approved, bot is merging ⏳

#109 [13.0][FIX] ddmrp_packaging: use computed, stored, readonly-false
  ddmrp_packaging/models/stock_buffer.py
Labels: approved, bot is merging ⏳

#110 [13.0][FIX] ddmrp stock.buffer sellers
  ddmrp/models/stock_buffer.py
Labels: approved, bot is merging ⏳

#111 [13.0][FIX] ddmrp: incorrect default ordering.
  ddmrp/models/stock_buffer.py
Labels: approved, bot is merging ⏳
