Repository OCA/ddmrp, pull requests merged in 2021-06, with the labels that each got.

#128 [13.0][IMP] ddmrp improve po line on hand status
  ddmrp/models/purchase_order.py
  ddmrp/views/purchase_order_line_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#135 [14.0] [MIG] ddmrp_chatter
  ddmrp_chatter/README.rst
  ddmrp_chatter/__init__.py
  ddmrp_chatter/__manifest__.py
  ddmrp_chatter/i18n/ddmrp_chatter.pot
  ddmrp_chatter/models/__init__.py
  ddmrp_chatter/models/stock_buffer.py
  ddmrp_chatter/readme/CONTRIBUTORS.rst
  ddmrp_chatter/readme/DESCRIPTION.rst
  ddmrp_chatter/readme/HISTORY.rst
  ddmrp_chatter/static/description/icon.png
  ddmrp_chatter/static/description/index.html
  ddmrp_chatter/views/ddmrp_buffer_view.xml
  setup/ddmrp_chatter/odoo/addons/ddmrp_chatter
  setup/ddmrp_chatter/setup.py
Labels: bot is merging ⏳

#141 [14.0][IMP] ddmrp improve po line on hand status
  ddmrp/models/purchase_order.py
  ddmrp/views/purchase_order_line_view.xml
Labels: bot is merging ⏳

#144 [13.0][FIX] ddmrp: buffer profiles must be no-update
  ddmrp/__manifest__.py
  ddmrp/data/stock.buffer.profile.csv
  ddmrp/data/stock_buffer_profile_data.xml
  ddmrp/migrations/13.0.1.19.0/post-migration.py
Labels: approved, bot is merging ⏳

#143 [13.0][IMP] ddmrp_product_replace: auto update replacement buffers
  ddmrp/models/stock_move.py
  ddmrp_product_replace/models/__init__.py
  ddmrp_product_replace/models/stock_buffer.py
  ddmrp_product_replace/models/stock_move.py
Labels: approved, bot is merging ⏳, ready to merge

#146 [14.0][FIX] ddmrp: buffer profiles must be no-update
  ddmrp/__manifest__.py
  ddmrp/data/stock.buffer.profile.csv
  ddmrp/data/stock_buffer_profile_data.xml
  ddmrp/migrations/14.0.1.6.0/post-migration.py
Labels: approved, bot is merging ⏳

#106 [14.0] [MIG] ddmrp_adjustment
  ddmrp_adjustment/README.rst
  ddmrp_adjustment/__init__.py
  ddmrp_adjustment/__manifest__.py
  ddmrp_adjustment/i18n/ddmrp_adjustment.pot
  ddmrp_adjustment/models/__init__.py
  ddmrp_adjustment/models/ddmrp_adjustment.py
  ddmrp_adjustment/models/ddmrp_adjustment_demand.py
  ddmrp_adjustment/models/stock_buffer.py
  ddmrp_adjustment/readme/CONTRIBUTORS.rst
  ddmrp_adjustment/readme/DESCRIPTION.rst
  ddmrp_adjustment/readme/HISTORY.rst
  ddmrp_adjustment/readme/ROADMAP.rst
  ddmrp_adjustment/readme/USAGE.rst
  ddmrp_adjustment/security/ddmrp_security.xml
  ddmrp_adjustment/security/ir.model.access.csv
  ddmrp_adjustment/static/description/icon.png
  ddmrp_adjustment/static/description/index.html
  ddmrp_adjustment/tests/__init__.py
  ddmrp_adjustment/tests/test_adjustment_wizard.py
  ddmrp_adjustment/tests/test_adu_dlt_adjustment.py
  ddmrp_adjustment/tests/test_common.py
  ddmrp_adjustment/views/ddmrp_adjustment_demand_view.xml
  ddmrp_adjustment/views/ddmrp_adjustment_view.xml
  ddmrp_adjustment/views/stock_buffer_view.xml
  ddmrp_adjustment/wizards/__init__.py
  ddmrp_adjustment/wizards/ddmrp_adjustment_sheet.py
  ddmrp_adjustment/wizards/ddmrp_adjustment_wizard_view.xml
  setup/ddmrp_adjustment/odoo/addons/ddmrp_adjustment
  setup/ddmrp_adjustment/setup.py
Labels: approved, bot is merging ⏳

#137 [14.0] [MIG] ddmrp_packaging
  ddmrp_packaging/README.rst
  ddmrp_packaging/__init__.py
  ddmrp_packaging/__manifest__.py
  ddmrp_packaging/i18n/ddmrp_packaging.pot
  ddmrp_packaging/models/__init__.py
  ddmrp_packaging/models/stock_buffer.py
  ddmrp_packaging/readme/CONTRIBUTORS.rst
  ddmrp_packaging/readme/DESCRIPTION.rst
  ddmrp_packaging/readme/HISTORY.rst
  ddmrp_packaging/readme/INSTALL.rst
  ddmrp_packaging/static/description/icon.png
  ddmrp_packaging/static/description/index.html
  ddmrp_packaging/views/stock_buffer_view.xml
  setup/ddmrp_packaging/odoo/addons/ddmrp_packaging
  setup/ddmrp_packaging/setup.py
Labels: approved, bot is merging ⏳

#136 [14.0] [MIG] ddmrp_coverage_days
  ddmrp_coverage_days/README.rst
  ddmrp_coverage_days/__init__.py
  ddmrp_coverage_days/__manifest__.py
  ddmrp_coverage_days/i18n/ddmrp_coverage_days.pot
  ddmrp_coverage_days/models/__init__.py
  ddmrp_coverage_days/models/stock_buffer.py
  ddmrp_coverage_days/readme/CONTRIBUTORS.rst
  ddmrp_coverage_days/readme/DESCRIPTION.rst
  ddmrp_coverage_days/readme/HISTORY.rst
  ddmrp_coverage_days/static/description/icon.png
  ddmrp_coverage_days/static/description/index.html
  ddmrp_coverage_days/tests/__init__.py
  ddmrp_coverage_days/tests/test_ddmrp_coverage_days.py
  ddmrp_coverage_days/views/stock_buffer_views.xml
  setup/ddmrp_coverage_days/odoo/addons/ddmrp_coverage_days
  setup/ddmrp_coverage_days/setup.py
Labels: approved, bot is merging ⏳

#138 [14.0] [MIG] stock_buffer_capacity_limit
  setup/stock_buffer_capacity_limit/odoo/addons/stock_buffer_capacity_limit
  setup/stock_buffer_capacity_limit/setup.py
  stock_buffer_capacity_limit/README.rst
  stock_buffer_capacity_limit/__init__.py
  stock_buffer_capacity_limit/__manifest__.py
  stock_buffer_capacity_limit/i18n/stock_buffer_capacity_limit.pot
  stock_buffer_capacity_limit/models/__init__.py
  stock_buffer_capacity_limit/models/stock_buffer.py
  stock_buffer_capacity_limit/readme/CONTRIBUTORS.rst
  stock_buffer_capacity_limit/readme/DESCRIPTION.rst
  stock_buffer_capacity_limit/readme/HISTORY.rst
  stock_buffer_capacity_limit/static/description/icon.png
  stock_buffer_capacity_limit/static/description/index.html
  stock_buffer_capacity_limit/tests/__init__.py
  stock_buffer_capacity_limit/tests/test_stock_buffer_capacity_limit.py
  stock_buffer_capacity_limit/views/stock_buffer_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#140 [14.0] [MIG] ddmrp_cron_actions_as_job
  ddmrp_cron_actions_as_job/README.rst
  ddmrp_cron_actions_as_job/__init__.py
  ddmrp_cron_actions_as_job/__manifest__.py
  ddmrp_cron_actions_as_job/data/queue_job_channel_data.xml
  ddmrp_cron_actions_as_job/data/queue_job_function_data.xml
  ddmrp_cron_actions_as_job/i18n/ddmrp_cron_actions_as_job.pot
  ddmrp_cron_actions_as_job/models/__init__.py
  ddmrp_cron_actions_as_job/models/stock_buffer.py
  ddmrp_cron_actions_as_job/models/stock_move.py
  ddmrp_cron_actions_as_job/readme/CONTRIBUTORS.rst
  ddmrp_cron_actions_as_job/readme/DESCRIPTION.rst
  ddmrp_cron_actions_as_job/static/description/icon.png
  ddmrp_cron_actions_as_job/static/description/index.html
  ddmrp_cron_actions_as_job/tests/__init__.py
  ddmrp_cron_actions_as_job/tests/test_cron_actions_as_job.py
  setup/ddmrp_cron_actions_as_job/odoo/addons/ddmrp_cron_actions_as_job
  setup/ddmrp_cron_actions_as_job/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#139 [14.0] [MIG] stock_buffer_route
  setup/stock_buffer_route/odoo/addons/stock_buffer_route
  setup/stock_buffer_route/setup.py
  stock_buffer_route/README.rst
  stock_buffer_route/__init__.py
  stock_buffer_route/__manifest__.py
  stock_buffer_route/i18n/stock_buffer_route.pot
  stock_buffer_route/models/__init__.py
  stock_buffer_route/models/stock_buffer.py
  stock_buffer_route/readme/CONTRIBUTORS.rst
  stock_buffer_route/readme/DESCRIPTION.rst
  stock_buffer_route/readme/USAGE.rst
  stock_buffer_route/static/description/icon.png
  stock_buffer_route/static/description/index.html
  stock_buffer_route/tests/__init__.py
  stock_buffer_route/tests/test_stock_buffer_route.py
  stock_buffer_route/views/stock_buffer_views.xml
Labels: approved, bot is merging ⏳, ready to merge

#147 [14.0][IMP] ddmrp: add hook to extend auto-update buffers.
  ddmrp/models/stock_move.py
Labels: bot is merging ⏳
