Repository OCA/ddmrp, pull requests merged in 2022-02, with the labels that each got.

#187 [14][FWD] [FIX] Disable unarchiving buffer on product activation
  ddmrp/models/product_product.py
Labels: bot is merging ⏳

#180 [13.0][FIX] Disable unarchiving buffer on product activation
  ddmrp/models/product_product.py
Labels: approved, ready to merge, bot is merging ⏳

#199 [14.0][FIX] ddmrp: method moved to purchase.order.line model
  ddmrp/models/purchase_order.py
  ddmrp/models/stock_rule.py
Labels: approved, bot is merging ⏳

#202 [15.0][FIX] Disable unarchiving buffer on product activation
  ddmrp/models/product_product.py
Labels: bot is merging ⏳

#201 [15.0][MIG] ddmrp_history
  ddmrp_history/README.rst
  ddmrp_history/__init__.py
  ddmrp_history/__manifest__.py
  ddmrp_history/demo/ddmrp.history.csv
  ddmrp_history/i18n/ddmrp_history.pot
  ddmrp_history/i18n/es.po
  ddmrp_history/i18n/fr.po
  ddmrp_history/models/__init__.py
  ddmrp_history/models/ddmrp_history.py
  ddmrp_history/models/stock_buffer.py
  ddmrp_history/readme/CONTRIBUTORS.rst
  ddmrp_history/readme/CREDITS.rst
  ddmrp_history/readme/DESCRIPTION.rst
  ddmrp_history/readme/HISTORY.rst
  ddmrp_history/readme/INSTALL.rst
  ddmrp_history/readme/USAGE.rst
  ddmrp_history/security/ir.model.access.csv
  ddmrp_history/static/description/icon.png
  ddmrp_history/static/description/index.html
  ddmrp_history/tests/__init__.py
  ddmrp_history/tests/test_ddmrp_history.py
  ddmrp_history/views/ddmrp_history_view.xml
  ddmrp_history/views/stock_buffer_view.xml
  requirements.txt
  setup/ddmrp_history/odoo/addons/ddmrp_history
  setup/ddmrp_history/setup.py
Labels: bot is merging ⏳

#189 [14.0][FIX] ddmrp*: remove direct read of client action
  ddmrp/models/stock_buffer.py
  ddmrp/models/stock_picking.py
  ddmrp_product_replace/models/stock_buffer.py
Labels: approved, bot is merging ⏳

#203 [15.0][FIX] ddmrp: remove direct read of client action
  ddmrp/models/stock_buffer.py
  ddmrp/models/stock_picking.py
Labels: needs review, bot is merging ⏳

#186 [14.0] Fix quantity_in_progress computation
  ddmrp/models/stock_buffer.py
Labels: approved, bot is merging ⏳

#161 [13.0][IMP] ddmrp: add an index on 'stock_move_line.state'
  ddmrp/models/__init__.py
  ddmrp/models/stock_move_line.py
Labels: bot is merging ⏳

#204 [15.0][FIX] ddmrp: fix quantity_in_progress computation
  ddmrp/models/stock_buffer.py
Labels: bot is merging ⏳

#194 [14.0] Add ddmrp_purchase_hide_onhand_status
  ddmrp/wizards/res_config_settings.py
  ddmrp/wizards/res_config_settings_views.xml
  ddmrp_purchase_hide_onhand_status/__init__.py
  ddmrp_purchase_hide_onhand_status/__manifest__.py
  ddmrp_purchase_hide_onhand_status/models/__init__.py
  ddmrp_purchase_hide_onhand_status/models/purchase_order.py
  ddmrp_purchase_hide_onhand_status/readme/CONTRIBUTORS.rst
  ddmrp_purchase_hide_onhand_status/readme/DESCRIPTION.rst
  ddmrp_purchase_hide_onhand_status/tests/__init__.py
  ddmrp_purchase_hide_onhand_status/tests/test_ddmrp_purchase_hide_onhand_status.py
  ddmrp_purchase_hide_onhand_status/views/purchase_order_view.xml
  setup/ddmrp_purchase_hide_onhand_status/odoo/addons/ddmrp_purchase_hide_onhand_status
  setup/ddmrp_purchase_hide_onhand_status/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#206 [15.0][IMP] ddmrp: add an index on 'stock_move_line.state'
  ddmrp/models/__init__.py
  ddmrp/models/stock_move_line.py
Labels: bot is merging ⏳

#205 [14.0][IMP] ddmrp: add an index on 'stock_move_line.state'
  ddmrp/models/__init__.py
  ddmrp/models/stock_move_line.py
Labels: bot is merging ⏳

#192 [14.0][IMP] ddmrp: add index on 'distributed_source_location_id'
  ddmrp/models/stock_buffer.py
Labels: bot is merging ⏳

#191 [13.0][IMP] ddmrp: add index on 'distributed_source_location_id'
  ddmrp/models/stock_buffer.py
Labels: approved, bot is merging ⏳

#207 [15.0] ddmrp: add index on 'distributed_source_location_id'
  ddmrp/models/stock_buffer.py
Labels: needs review, bot is merging ⏳

#208 [15.0][FIX] ddmrp: method moved to purchase.order.line model
  ddmrp/models/purchase_order.py
  ddmrp/models/stock_rule.py
Labels: bot is merging ⏳

#209 [15.0][MIG] ddmrp_cron_actions_as_job
  ddmrp_cron_actions_as_job/README.rst
  ddmrp_cron_actions_as_job/__init__.py
  ddmrp_cron_actions_as_job/__manifest__.py
  ddmrp_cron_actions_as_job/data/queue_job_channel_data.xml
  ddmrp_cron_actions_as_job/data/queue_job_function_data.xml
  ddmrp_cron_actions_as_job/i18n/ddmrp_cron_actions_as_job.pot
  ddmrp_cron_actions_as_job/i18n/pt_BR.po
  ddmrp_cron_actions_as_job/models/__init__.py
  ddmrp_cron_actions_as_job/models/stock_buffer.py
  ddmrp_cron_actions_as_job/models/stock_move.py
  ddmrp_cron_actions_as_job/readme/CONTRIBUTORS.rst
  ddmrp_cron_actions_as_job/readme/DESCRIPTION.rst
  ddmrp_cron_actions_as_job/static/description/icon.png
  ddmrp_cron_actions_as_job/static/description/index.html
  ddmrp_cron_actions_as_job/tests/__init__.py
  ddmrp_cron_actions_as_job/tests/test_cron_actions_as_job.py
  setup/ddmrp_cron_actions_as_job/odoo/addons/ddmrp_cron_actions_as_job
  setup/ddmrp_cron_actions_as_job/setup.py
Labels: bot is merging ⏳
