Repository OCA/ddmrp, pull requests merged in 2023-05, with the labels that each got.

#229 [14.0][FIX] added case when resupply from another warehouse
  ddmrp/__manifest__.py
  ddmrp/migrations/14.0.1.14.1/post-fix_distributed_source_location.py
  ddmrp/models/stock_buffer.py
  ddmrp/tests/common.py
  ddmrp/tests/test_ddmrp.py
Labels: bot is merging ⏳

#256 [15.0][FIX] ddmrp, case when origin warehouse has 2 steps to delivery
  ddmrp/__manifest__.py
  ddmrp/migrations/15.0.1.4.1/post-fix_distributed_source_location.py
  ddmrp/models/stock_buffer.py
  ddmrp/tests/common.py
  ddmrp/tests/test_ddmrp.py
Labels: bot is merging ⏳

#253 [14.0][IMP] ddmrp: Redesign stock buffer form view
  ddmrp/models/stock_buffer.py
  ddmrp/views/stock_buffer_view.xml
Labels: bot is merging ⏳, Pending to fw/back port

#254 [14.0][IMP] ddmrp_adjustment: Adapt view to new Stock Buffer view design
  ddmrp_adjustment/views/stock_buffer_view.xml
Labels: bot is merging ⏳

#255 [14.0][IMP] ddmrp_coverage_days: Adapt view to new Stock Buffer view design
  ddmrp_coverage_days/models/stock_buffer.py
  ddmrp_coverage_days/views/stock_buffer_views.xml
Labels: Pending to fw/back port

#258 [13.0][IMP] ddmrp: Add links
  ddmrp/__manifest__.py
  ddmrp/models/product_product.py
  ddmrp/models/stock_buffer.py
  ddmrp/views/mrp_bom_view.xml
  ddmrp/views/product_view.xml
  ddmrp/views/stock_buffer_view.xml
Labels: bot is merging ⏳

#259 [15.0][IMP] ddmrp: Add links
  ddmrp/__manifest__.py
  ddmrp/models/product_product.py
  ddmrp/models/stock_buffer.py
  ddmrp/views/mrp_bom_view.xml
  ddmrp/views/product_view.xml
  ddmrp/views/stock_buffer_view.xml
Labels: bot is merging ⏳

#257 [13.0][IMP] ddmrp: Redesign stock buffer form view
  ddmrp/models/stock_buffer.py
  ddmrp/views/stock_buffer_view.xml
  ddmrp_sale/models/stock_buffer.py
  ddmrp_sale/views/stock_buffer_view.xml
Labels: bot is merging ⏳

#260 [13.0][IMP] ddmrp_adjustment: Adapt view to new Stock Buffer view design
  ddmrp_adjustment/views/stock_buffer_view.xml
Labels: bot is merging ⏳

#261 [13.0][IMP] ddmrp_coverage_days: Adapt view to new Stock Buffer view design
  ddmrp_coverage_days/models/stock_buffer.py
  ddmrp_coverage_days/views/stock_buffer_views.xml
Labels: bot is merging ⏳

#262 [15.0][IMP] ddmrp: Redesign stock buffer form view
  ddmrp/models/stock_buffer.py
  ddmrp/views/stock_buffer_view.xml
Labels: bot is merging ⏳

#263 [15.0][IMP] ddmrp_adjustment: Adapt view to new Stock Buffer view design
  ddmrp_adjustment/views/stock_buffer_view.xml
Labels: bot is merging ⏳

#264 [15.0][IMP] ddmrp_coverage_days: Adapt view to new Stock Buffer view design
  ddmrp_coverage_days/models/stock_buffer.py
  ddmrp_coverage_days/views/stock_buffer_views.xml
Labels: bot is merging ⏳

#266 [14.0][FIX] ddmrp: Correct function parameters in get stock move values
  ddmrp/models/stock_rule.py
Labels: bot is merging ⏳

#267 [13.0][FIX] ddmrp: Correct function parameters in get stock move values
  ddmrp/models/stock_rule.py
Labels: bot is merging ⏳

#269 [14.0][FIX] ddmrp: Remove active in domains
  ddmrp/models/stock_buffer.py
Labels: bot is merging ⏳, Pending to fw/back port

#271 [15.0][FIX] ddmrp: Remove active in domains
  ddmrp/models/stock_buffer.py
Labels: bot is merging ⏳

#270 [13.0][FIX] ddmrp: Remove active in domains
  ddmrp/models/stock_buffer.py
Labels: bot is merging ⏳

#265 [13.0][IMP] ddmrp: introduce specific security groups
  ddmrp/__manifest__.py
  ddmrp/demo/ddmrp_demo_user.xml
  ddmrp/security/ddmrp_groups.xml
  ddmrp/security/ddmrp_rules.xml
  ddmrp/security/ir.model.access.csv
  ddmrp/security/stock_buffer_manual_procurement_security.xml
  ddmrp/tests/common.py
  ddmrp/wizards/res_config_settings_views.xml
  stock_buffer_route/tests/test_stock_buffer_route.py
Labels: bot is merging ⏳

#268 [13.0][IMP] ddmrp: add execution chart to buffer summary
  ddmrp/models/stock_buffer.py
  ddmrp/static/src/js/list_renderer_buffer_info.js
  ddmrp/views/stock_buffer_view.xml
  ddmrp_history/models/stock_buffer.py
Labels: bot is merging ⏳

#272 [13.0][FIX] ddmrp: fix inheritance not returning anything
  ddmrp/models/mrp_production.py
Labels: approved, bot is merging ⏳, Pending to fw/back port

#273 [14.0][IMP] ddmrp: introduce specific security groups
  ddmrp/__manifest__.py
  ddmrp/demo/ddmrp_demo_user.xml
  ddmrp/security/ddmrp_groups.xml
  ddmrp/security/ddmrp_rules.xml
  ddmrp/security/ir.model.access.csv
  ddmrp/security/stock_buffer_manual_procurement_security.xml
  ddmrp/tests/common.py
  ddmrp/wizards/res_config_settings_views.xml
  stock_buffer_route/tests/test_stock_buffer_route.py
Labels: bot is merging ⏳

#275 [14.0][IMP] ddmrp: add execution chart to buffer summary
  ddmrp/models/stock_buffer.py
  ddmrp/static/src/js/list_renderer_buffer_info.js
  ddmrp/views/stock_buffer_view.xml
  ddmrp_history/models/stock_buffer.py
Labels: bot is merging ⏳

#276 [15.0][IMP] ddmrp: add execution chart to buffer summary
  ddmrp/models/stock_buffer.py
  ddmrp/static/src/js/list_renderer_buffer_info.js
  ddmrp/views/stock_buffer_view.xml
  ddmrp_history/models/stock_buffer.py
Labels: bot is merging ⏳

#278 [13.0][IMP] ddmrp: Add hook to get ADU calculation horizon
  ddmrp/models/stock_buffer.py
Labels: bot is merging ⏳

#277 [14.0][FIX] ddmrp: remove unneded inheritance
  ddmrp/models/mrp_production.py
Labels: bot is merging ⏳

#281 [15.0][FIX] ddmrp: remove unneded inheritance
  ddmrp/models/mrp_production.py
Labels: bot is merging ⏳
