Repository OCA/ddmrp, pull requests merged in 2023-12, with the labels that each got.

#354 [16.0][MIG] ddmrp_product_replace
  ddmrp_product_replace/README.rst
  ddmrp_product_replace/__init__.py
  ddmrp_product_replace/__manifest__.py
  ddmrp_product_replace/i18n/ddmrp_product_replace.pot
  ddmrp_product_replace/i18n/es.po
  ddmrp_product_replace/i18n/it.po
  ddmrp_product_replace/i18n/pt_BR.po
  ddmrp_product_replace/models/__init__.py
  ddmrp_product_replace/models/stock_buffer.py
  ddmrp_product_replace/models/stock_move.py
  ddmrp_product_replace/readme/CONTRIBUTORS.rst
  ddmrp_product_replace/readme/CREDITS.rst
  ddmrp_product_replace/readme/DESCRIPTION.rst
  ddmrp_product_replace/readme/ROADMAP.rst
  ddmrp_product_replace/readme/USAGE.rst
  ddmrp_product_replace/security/ir.model.access.csv
  ddmrp_product_replace/static/description/icon.png
  ddmrp_product_replace/static/description/index.html
  ddmrp_product_replace/tests/__init__.py
  ddmrp_product_replace/tests/test_product_replace.py
  ddmrp_product_replace/views/stock_buffer_view.xml
  ddmrp_product_replace/wizards/__init__.py
  ddmrp_product_replace/wizards/ddmrp_product_replace.py
  ddmrp_product_replace/wizards/ddmrp_product_replace_view.xml
  ddmrp_product_replace/wizards/make_procurement_buffer.py
  ddmrp_product_replace/wizards/make_procurement_buffer_view.xml
  setup/ddmrp_product_replace/odoo/addons/ddmrp_product_replace
  setup/ddmrp_product_replace/setup.py
Labels: approved, bot is merging ⏳

#351 [16.0][MIG] stock_buffer_route
  setup/stock_buffer_route/odoo/addons/stock_buffer_route
  setup/stock_buffer_route/setup.py
  stock_buffer_route/README.rst
  stock_buffer_route/__init__.py
  stock_buffer_route/__manifest__.py
  stock_buffer_route/i18n/pt_BR.po
  stock_buffer_route/i18n/stock_buffer_route.pot
  stock_buffer_route/models/__init__.py
  stock_buffer_route/models/stock_buffer.py
  stock_buffer_route/readme/CONTRIBUTORS.rst
  stock_buffer_route/readme/DESCRIPTION.rst
  stock_buffer_route/readme/USAGE.rst
  stock_buffer_route/static/description/icon.png
  stock_buffer_route/static/description/index.html
  stock_buffer_route/tests/__init__.py
  stock_buffer_route/tests/test_stock_buffer_route.py
  stock_buffer_route/views/stock_buffer_views.xml
Labels: bot is merging ⏳

#357 [16.0][MIG] ddmrp_exclude_moves_adu_calc
  ddmrp_exclude_moves_adu_calc/README.rst
  ddmrp_exclude_moves_adu_calc/__init__.py
  ddmrp_exclude_moves_adu_calc/__manifest__.py
  ddmrp_exclude_moves_adu_calc/i18n/ddmrp_exclude_moves_adu_calc.pot
  ddmrp_exclude_moves_adu_calc/i18n/es.po
  ddmrp_exclude_moves_adu_calc/i18n/fr.po
  ddmrp_exclude_moves_adu_calc/i18n/it.po
  ddmrp_exclude_moves_adu_calc/i18n/pt_BR.po
  ddmrp_exclude_moves_adu_calc/models/__init__.py
  ddmrp_exclude_moves_adu_calc/models/stock_buffer.py
  ddmrp_exclude_moves_adu_calc/models/stock_location.py
  ddmrp_exclude_moves_adu_calc/models/stock_move.py
  ddmrp_exclude_moves_adu_calc/readme/CONTRIBUTORS.rst
  ddmrp_exclude_moves_adu_calc/readme/CREDITS.rst
  ddmrp_exclude_moves_adu_calc/readme/DESCRIPTION.rst
  ddmrp_exclude_moves_adu_calc/readme/HISTORY.rst
  ddmrp_exclude_moves_adu_calc/readme/USAGE.rst
  ddmrp_exclude_moves_adu_calc/static/description/icon.png
  ddmrp_exclude_moves_adu_calc/static/description/index.html
  ddmrp_exclude_moves_adu_calc/tests/__init__.py
  ddmrp_exclude_moves_adu_calc/tests/test_ddmrp.py
  ddmrp_exclude_moves_adu_calc/views/stock_location_view.xml
  ddmrp_exclude_moves_adu_calc/views/stock_move_view.xml
  setup/ddmrp_exclude_moves_adu_calc/odoo/addons/ddmrp_exclude_moves_adu_calc
  setup/ddmrp_exclude_moves_adu_calc/setup.py
Labels: bot is merging ⏳

#356 [16.0][MIG] ddmrp_adjustment
  ddmrp_adjustment/README.rst
  ddmrp_adjustment/__init__.py
  ddmrp_adjustment/__manifest__.py
  ddmrp_adjustment/i18n/ddmrp_adjustment.pot
  ddmrp_adjustment/i18n/es.po
  ddmrp_adjustment/i18n/it.po
  ddmrp_adjustment/i18n/pt_BR.po
  ddmrp_adjustment/models/__init__.py
  ddmrp_adjustment/models/ddmrp_adjustment.py
  ddmrp_adjustment/models/ddmrp_adjustment_demand.py
  ddmrp_adjustment/models/stock_buffer.py
  ddmrp_adjustment/readme/CONTRIBUTORS.rst
  ddmrp_adjustment/readme/DESCRIPTION.rst
  ddmrp_adjustment/readme/HISTORY.rst
  ddmrp_adjustment/readme/ROADMAP.rst
  ddmrp_adjustment/readme/USAGE.rst
  ddmrp_adjustment/security/ddmrp_security.xml
  ddmrp_adjustment/security/ir.model.access.csv
  ddmrp_adjustment/static/description/icon.png
  ddmrp_adjustment/static/description/index.html
  ddmrp_adjustment/tests/__init__.py
  ddmrp_adjustment/tests/test_adjustment_wizard.py
  ddmrp_adjustment/tests/test_adu_dlt_adjustment.py
  ddmrp_adjustment/tests/test_common.py
  ddmrp_adjustment/views/ddmrp_adjustment_demand_view.xml
  ddmrp_adjustment/views/ddmrp_adjustment_view.xml
  ddmrp_adjustment/views/stock_buffer_view.xml
  ddmrp_adjustment/wizards/__init__.py
  ddmrp_adjustment/wizards/ddmrp_adjustment_sheet.py
  ddmrp_adjustment/wizards/ddmrp_adjustment_wizard_view.xml
  setup/ddmrp_adjustment/odoo/addons/ddmrp_adjustment
  setup/ddmrp_adjustment/setup.py
Labels: bot is merging ⏳

#358 [16.0][FIX] ddmrp: minor leftovers from migration
  ddmrp/static/src/widgets/stock_buffer_info.esm.js
  ddmrp/views/mrp_production_view.xml
  ddmrp/views/purchase_order_line_view.xml
  ddmrp/views/stock_buffer_view.xml
  ddmrp/wizards/res_config_settings_views.xml
Labels: bot is merging ⏳

#361 [16.0][FIX] ddmrp: rename filter planning_priority_level
  ddmrp/views/stock_buffer_view.xml
Labels: Pending to fw/back port

#363 [16.0][FIX] ddmrp: Boolean toggle should not autosave
  ddmrp/views/stock_buffer_view.xml
Labels: bot is merging ⏳

#364 [14.0][FIX] ddmrp_product_replace: do not copy 'Considered as demand' field
  ddmrp_product_replace/models/stock_buffer.py
Labels: bot is merging ⏳, Pending to fw/back port

#368 [16.0][FIX] ddmrp_product_replace: do not copy 'Considered as demand' field
  ddmrp_product_replace/models/stock_buffer.py
Labels: needs review, bot is merging ⏳

#366 [13.0][FIX] ddmrp_product_replace: do not copy 'Considered as demand' field
  ddmrp_product_replace/models/stock_buffer.py
Labels: bot is merging ⏳

#367 [15.0][FIX] ddmrp_product_replace: do not copy 'Considered as demand' field
  ddmrp_product_replace/models/stock_buffer.py
Labels: needs review, bot is merging ⏳
