Repository OCA/ddmrp, pull requests merged in 2023-07, with the labels that each got.

#250 [14.0][FIX] ddmrp: use archived locations in the ADU computation
  ddmrp/models/stock_buffer.py
Labels: approved, ready to merge, bot is merging ⏳

#299 [15.0][FW] ddmrp: multiple ports from 14.0
  .oca/oca-port/blacklist/ddmrp.json
Labels: bot is merging ⏳

#300 [14.0][FW] ddmrp: multiple ports from 15.0
  .oca/oca-port/blacklist/ddmrp.json
  ddmrp/models/__init__.py
  ddmrp/models/mrp_move.py
  ddmrp/models/stock_buffer.py
  ddmrp_warning/models/stock_buffer.py
Labels: approved, bot is merging ⏳

#301 [15.0][FW] [14.0][FIX] ddmrp: use archived locations in the ADU computation
  ddmrp/models/stock_buffer.py
Labels: bot is merging ⏳

#302 [13.0][FIX] ddmrp: incorrect handling of reservation UoM computing demand.
  ddmrp/models/stock_buffer.py
  ddmrp/tests/common.py
  ddmrp/tests/test_ddmrp.py
Labels: approved, bot is merging ⏳

#303 [14.0][FIX] ddmrp: incorrect handling of reservation UoM computing demand.
  ddmrp/models/stock_buffer.py
  ddmrp/tests/common.py
  ddmrp/tests/test_ddmrp.py
Labels: bot is merging ⏳

#304 [15.0][FIX] ddmrp: incorrect handling of reservation UoM computing demand.
  ddmrp/models/stock_buffer.py
  ddmrp/tests/common.py
  ddmrp/tests/test_ddmrp.py
Labels: bot is merging ⏳

#305 [13.0][FIX] ddmrp: consider multicompany when finding BoMs
  ddmrp/models/mrp_bom.py
  ddmrp/models/stock_buffer.py
  ddmrp/tests/common.py
  ddmrp/tests/test_ddmrp.py
Labels: approved, bot is merging ⏳

#306 [14.0][FIX] ddmrp: consider multicompany when finding BoMs
  ddmrp/models/mrp_bom.py
  ddmrp/models/stock_buffer.py
  ddmrp/tests/common.py
  ddmrp/tests/test_ddmrp.py
Labels: bot is merging ⏳

#307 [15.0][FIX] ddmrp: consider multicompany when finding BoMs
  ddmrp/models/mrp_bom.py
  ddmrp/models/stock_buffer.py
  ddmrp/tests/common.py
  ddmrp/tests/test_ddmrp.py
Labels: bot is merging ⏳
