Repository OCA/ddmrp, pull requests merged in 2023-06, with the labels that each got.

#280 [13.0][IMP] ddmrp: Add missing ADU calculation horizon calls
  ddmrp/models/stock_buffer.py
Labels: bot is merging ⏳, Pending to fw/back port

#287 [14.0][FIX] ddmrp_warning: access warnings report multi-company environment
  ddmrp_warning/__manifest__.py
  ddmrp_warning/models/ddmrp_warning_item.py
  ddmrp_warning/security/ddmrp_warning_rules.xml
  ddmrp_warning/views/ddmrp_warning_item_views.xml
Labels: bot is merging ⏳

#288 [15.0][FIX] ddmrp_warning: access warnings report multi-company environment
  ddmrp_warning/__manifest__.py
  ddmrp_warning/models/ddmrp_warning_item.py
  ddmrp_warning/security/ddmrp_warning_rules.xml
  ddmrp_warning/views/ddmrp_warning_item_views.xml
Labels: bot is merging ⏳

#289 [13.0][FIX] ddmrp: Check sublocations in Stock Buffers
  ddmrp/models/stock_buffer.py
Labels: bot is merging ⏳

#290 [15.0][FIX] ddmrp: Check sublocations in Stock Buffers
  ddmrp/models/stock_buffer.py
Labels: bot is merging ⏳

#285 [14.0][IMP] stock_buffer_route: Adapt view to new Stock Buffer view design
  stock_buffer_route/views/stock_buffer_views.xml
Labels: bot is merging ⏳

#291 [13.0][IMP] stock_buffer_route: Adapt view to new Stock Buffer view dessign
  stock_buffer_route/views/stock_buffer_views.xml
Labels: bot is merging ⏳

#292 [15.0][IMP] stock_buffer_route: Adapt view to new Stock Buffer view dessign
  stock_buffer_route/views/stock_buffer_views.xml
Labels: bot is merging ⏳

#293 [13.0][FIX] ddmrp_warning: delete warnings on cascade with the buffer.
  ddmrp_warning/models/ddmrp_warning_item.py
  ddmrp_warning/views/ddmrp_warning_item_views.xml
Labels: approved, bot is merging ⏳

#294 [14.0][FIX] ddmrp_warning: delete warnings on cascade with the buffer.
  ddmrp_warning/models/ddmrp_warning_item.py
  ddmrp_warning/views/ddmrp_warning_item_views.xml
Labels: bot is merging ⏳

#296 [13.0][IMP] ddmrp: show outside DLT quantity details in buffer form
  ddmrp/views/stock_buffer_view.xml
Labels: bot is merging ⏳

#297 [14.0][IMP] ddmrp: show outside DLT quantity details in buffer form
  ddmrp/views/stock_buffer_view.xml
Labels: bot is merging ⏳

#298 [15.0][IMP] ddmrp: show outside DLT quantity details in buffer form
  ddmrp/views/stock_buffer_view.xml
Labels: bot is merging ⏳
