Repository OCA/ddmrp, pull requests merged in 2023-11, with the labels that each got.

#330 [13.0][FIX]ddmrp: initialize defaultdict with actual model
  ddmrp/models/stock_buffer.py
Labels: bot is merging ⏳, Pending to fw/back port

#333 [15.0][FIX]ddmrp: initialize defaultdict with actual model
  ddmrp/models/stock_buffer.py
Labels: bot is merging ⏳

#334 [16.0][FIX]ddmrp: initialize defaultdict with actual model
  ddmrp/models/stock_buffer.py
Labels: bot is merging ⏳

#332 [14.0][UPD] repo template
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  README.md
  ddmrp/demo/res_partner_demo.xml
  ddmrp/views/product_adu_calculation_method_view.xml
  ddmrp/views/stock_buffer_profile_lead_time_view.xml
  ddmrp/views/stock_buffer_profile_variability_view.xml
  ddmrp/views/stock_buffer_profile_view.xml
  ddmrp/wizards/make_procurement_buffer_view.xml
  ddmrp_adjustment/views/ddmrp_adjustment_view.xml
  ddmrp_purchase_hide_onhand_status/views/purchase_order_view.xml
Labels: bot is merging ⏳

#331 [14.0][FIX]ddmrp: initialize defaultdict with actual model
  ddmrp/models/stock_buffer.py
Labels: bot is merging ⏳

#335 [16.0][FIX] ddmrp_history: adjust after latest bokeh widget changes.
  ddmrp_history/models/stock_buffer.py
Labels: bot is merging ⏳

#336 [16.0][FIX] ddmrp_history: remove blank space after charts
  ddmrp_history/models/stock_buffer.py
  ddmrp_history/views/stock_buffer_view.xml
Labels: bot is merging ⏳

#309 [14.0][IMP] ddmrp: Allow inheritance in the report BoM Lead Time
  ddmrp/report/bom_structure.py
  ddmrp/report/mrp_report_bom_structure.py
  ddmrp/report/mrp_report_bom_structure.xml
Labels: bot is merging ⏳, Pending to fw/back port

#338 [13.0][IMP] ddmrp: Allow inheritance in the report BoM Lead Time
  ddmrp/report/bom_structure.py
  ddmrp/report/mrp_report_bom_structure.py
  ddmrp/report/mrp_report_bom_structure.xml
Labels: bot is merging ⏳

#337 [15.0][IMP] ddmrp: Allow inheritance in the report BoM Lead Time
  ddmrp/report/bom_structure.py
  ddmrp/report/mrp_report_bom_structure.py
  ddmrp/report/mrp_report_bom_structure.xml
Labels: bot is merging ⏳

#340 [16.0][IMP] ddmrp: Add new ADU calculation method
  ddmrp/data/product_adu_calculation_method_data.xml
  ddmrp/models/product_adu_calculation_method.py
  ddmrp/models/stock_buffer.py
  ddmrp/tests/test_ddmrp.py
  ddmrp/views/stock_buffer_view.xml
Labels: bot is merging ⏳

#341 [14.0][IMP] ddmrp*: Add stored fields and remove non used
  ddmrp/models/stock_buffer.py
  ddmrp/models/stock_move_line.py
  ddmrp/views/stock_buffer_view.xml
  ddmrp_product_replace/models/stock_buffer.py
  ddmrp_product_replace/tests/test_product_replace.py
  stock_buffer_capacity_limit/models/stock_buffer.py
Labels: bot is merging ⏳, Pending to fw/back port

#345 [15.0][IMP] ddmrp*: Add stored fields and remove non used
  ddmrp/models/stock_buffer.py
  ddmrp/models/stock_move_line.py
  ddmrp/views/stock_buffer_view.xml
  ddmrp_product_replace/models/stock_buffer.py
  ddmrp_product_replace/tests/test_product_replace.py
  stock_buffer_capacity_limit/models/stock_buffer.py
Labels: bot is merging ⏳

#346 [16.0][IMP] ddmrp: Add stored fields and remove non-used ones
  ddmrp/models/stock_buffer.py
  ddmrp/models/stock_move_line.py
  ddmrp/views/stock_buffer_view.xml
Labels: bot is merging ⏳

#325 [14.0][IMP] ddmrp: Stock Buffers must be unique in product/location combina…
  ddmrp/__manifest__.py
  ddmrp/models/stock_buffer.py
  ddmrp/security/ir.model.access.csv
  ddmrp/tests/common.py
  ddmrp/tests/test_ddmrp.py
  ddmrp/tests/test_ddmrp_distributed_source_location.py
  ddmrp/tests/test_distributed_max_proc_time.py
  ddmrp/views/stock_buffer_view.xml
  ddmrp/wizards/__init__.py
  ddmrp/wizards/ddmrp_duplicate_buffer.py
  ddmrp/wizards/ddmrp_duplicate_buffer.xml
Labels: bot is merging ⏳, Pending to fw/back port

#342 [16.0][MIG] stock_buffer_sales_analysis
  setup/stock_buffer_sales_analysis/odoo/addons/stock_buffer_sales_analysis
  setup/stock_buffer_sales_analysis/setup.py
  stock_buffer_sales_analysis/README.rst
  stock_buffer_sales_analysis/__init__.py
  stock_buffer_sales_analysis/__manifest__.py
  stock_buffer_sales_analysis/i18n/pt_BR.po
  stock_buffer_sales_analysis/i18n/stock_buffer_sales_analysis.pot
  stock_buffer_sales_analysis/models/__init__.py
  stock_buffer_sales_analysis/models/stock_buffer.py
  stock_buffer_sales_analysis/readme/CONTRIBUTORS.rst
  stock_buffer_sales_analysis/readme/CREDITS.rst
  stock_buffer_sales_analysis/readme/DESCRIPTION.rst
  stock_buffer_sales_analysis/static/description/icon.png
  stock_buffer_sales_analysis/static/description/index.html
  stock_buffer_sales_analysis/views/stock_buffer_views.xml
Labels: bot is merging ⏳

#343 [16.0][FIX] ddmrp: Calculate estimate_date_to with calendar methods
  ddmrp/tests/test_ddmrp.py
Labels: bot is merging ⏳, Pending to fw/back port

#279 [13.0][IMP] ddmrp: Stock Buffers must be unique in product/location combination
  ddmrp/__manifest__.py
  ddmrp/models/stock_buffer.py
  ddmrp/tests/common.py
  ddmrp/tests/test_ddmrp.py
  ddmrp/tests/test_ddmrp_distributed_source_location.py
  ddmrp/tests/test_distributed_max_proc_time.py
  ddmrp/views/stock_buffer_view.xml
  ddmrp/wizards/__init__.py
  ddmrp/wizards/ddmrp_duplicate_buffer.py
  ddmrp/wizards/ddmrp_duplicate_buffer.xml
Labels: needs fixing, bot is merging ⏳

#347 [15.0][IMP] ddmrp: Stock Buffers must be unique in product/location combination
  ddmrp/__manifest__.py
  ddmrp/models/stock_buffer.py
  ddmrp/security/ir.model.access.csv
  ddmrp/tests/common.py
  ddmrp/tests/test_ddmrp.py
  ddmrp/tests/test_ddmrp_distributed_source_location.py
  ddmrp/tests/test_distributed_max_proc_time.py
  ddmrp/views/stock_buffer_view.xml
  ddmrp/wizards/__init__.py
  ddmrp/wizards/ddmrp_duplicate_buffer.py
  ddmrp/wizards/ddmrp_duplicate_buffer.xml
Labels: bot is merging ⏳

#348 [16.0][IMP] ddmrp: Stock Buffers must be unique in product/location combination
  ddmrp/__manifest__.py
  ddmrp/models/stock_buffer.py
  ddmrp/security/ir.model.access.csv
  ddmrp/tests/common.py
  ddmrp/tests/test_ddmrp.py
  ddmrp/tests/test_ddmrp_distributed_source_location.py
  ddmrp/tests/test_distributed_max_proc_time.py
  ddmrp/views/stock_buffer_view.xml
  ddmrp/wizards/__init__.py
  ddmrp/wizards/ddmrp_duplicate_buffer.py
  ddmrp/wizards/ddmrp_duplicate_buffer.xml
Labels: bot is merging ⏳

#350 [15.0][FIX] ddmrp: Calculate estimate_date_to with calendar methods
  ddmrp/tests/test_ddmrp.py
Labels: bot is merging ⏳

#349 [14.0][FIX] ddmrp: Calculate estimate_date_to with calendar methods
  ddmrp/tests/test_ddmrp.py
Labels: bot is merging ⏳
