Repository OCA/ddmrp, pull requests merged in 2024-08, with the labels that each got.

#488 [16.0][IMP] ddmrp_warning: various improvements
  ddmrp_warning/data/ddmrp_warning_definition_data.xml
  ddmrp_warning/models/ddmrp_warning_definition.py
  ddmrp_warning/models/ddmrp_warning_item.py
  ddmrp_warning/models/stock_buffer.py
  ddmrp_warning/tests/test_ddmrp_warning.py
Labels: bot is merging ⏳, Pending to fw/back port

#491 [17.0][IMP] ddmrp_warning: various improvements
  ddmrp_warning/data/ddmrp_warning_definition_data.xml
  ddmrp_warning/models/ddmrp_warning_definition.py
  ddmrp_warning/models/ddmrp_warning_item.py
  ddmrp_warning/models/stock_buffer.py
  ddmrp_warning/tests/test_ddmrp_warning.py
Labels: bot is merging ⏳

#490 [15.0][IMP] ddmrp_warning: various improvements
  ddmrp_warning/data/ddmrp_warning_definition_data.xml
  ddmrp_warning/models/ddmrp_warning_definition.py
  ddmrp_warning/models/ddmrp_warning_item.py
  ddmrp_warning/models/stock_buffer.py
  ddmrp_warning/tests/test_ddmrp_warning.py
Labels: bot is merging ⏳

#486 [16.0][ADD] ddmrp_sale_dropshipping
  ddmrp_sale_dropshipping/README.rst
  ddmrp_sale_dropshipping/__init__.py
  ddmrp_sale_dropshipping/__manifest__.py
  ddmrp_sale_dropshipping/models/__init__.py
  ddmrp_sale_dropshipping/models/stock_buffer.py
  ddmrp_sale_dropshipping/readme/CONTRIBUTORS.rst
  ddmrp_sale_dropshipping/readme/DESCRIPTION.rst
  ddmrp_sale_dropshipping/static/description/icon.png
  ddmrp_sale_dropshipping/static/description/index.html
  ddmrp_sale_dropshipping/tests/__init__.py
  ddmrp_sale_dropshipping/tests/test_ddmrp_sale_dropshipping.py
  setup/ddmrp_sale_dropshipping/odoo/addons/ddmrp_sale_dropshipping
  setup/ddmrp_sale_dropshipping/setup.py
Labels: approved, ready to merge, bot is merging ⏳
