Repository OCA/ddmrp, pull requests merged in 2024-06, with the labels that each got.

#423 [16.0][IMP] ddmrp_adjustment: visualize parent DAFs
  ddmrp_adjustment/models/ddmrp_adjustment_demand.py
  ddmrp_adjustment/models/stock_buffer.py
  ddmrp_adjustment/tests/test_adu_dlt_adjustment.py
  ddmrp_adjustment/views/ddmrp_adjustment_demand_view.xml
  ddmrp_adjustment/views/stock_buffer_view.xml
Labels: bot is merging ⏳, Pending to fw/back port

#462 [15.0][IMP] ddmrp_adjustment: visualize parent DAFs
  ddmrp_adjustment/models/ddmrp_adjustment_demand.py
  ddmrp_adjustment/models/stock_buffer.py
  ddmrp_adjustment/tests/test_adu_dlt_adjustment.py
  ddmrp_adjustment/views/ddmrp_adjustment_demand_view.xml
  ddmrp_adjustment/views/stock_buffer_view.xml
Labels: bot is merging ⏳

#464 [13.0][IMP] ddmrp_adjustment: visualize parent DAFs
  ddmrp_adjustment/models/ddmrp_adjustment_demand.py
  ddmrp_adjustment/models/stock_buffer.py
  ddmrp_adjustment/tests/test_adu_dlt_adjustment.py
  ddmrp_adjustment/views/ddmrp_adjustment_demand_view.xml
  ddmrp_adjustment/views/stock_buffer_view.xml
Labels: bot is merging ⏳

#466 [17.0][IMP] ddmrp: new icon for 17.0
  ddmrp/static/description/icon.png
Labels: approved

#465 [16.0][IMP] ddmrp_warning: add datetime, time and dateutil in safe_eval expression
  ddmrp_warning/models/ddmrp_warning_definition.py
Labels: bot is merging ⏳
