Repository OCA/ddmrp, pull requests merged in 2024-05, with the labels that each got.

#439 [16.0][IMP] ddmrp: reduce noise with auto-procure enabled
  ddmrp/models/stock_buffer.py
Labels: bot is merging ⏳

#440 [15.0][IMP] ddmrp: reduce noise with auto-procure enabled
  ddmrp/models/stock_buffer.py
Labels: bot is merging ⏳

#441 [14.0][IMP] ddmrp: reduce noise with auto-procure enabled
  ddmrp/models/stock_buffer.py
Labels: bot is merging ⏳

#443 [16.0][FIX] ddmrp_history: print correctly execution history.
  ddmrp_history/models/stock_buffer.py
Labels: bot is merging ⏳

#444 [15.0][FIX] ddmrp_history: print correctly execution history.
  ddmrp_history/models/stock_buffer.py
Labels: bot is merging ⏳

#445 [14.0][FIX] ddmrp_history: print correctly execution history.
  ddmrp_history/models/stock_buffer.py
Labels: bot is merging ⏳

#448 [16.0][IMP] ddmrp_history: add multicompany rules
  ddmrp_history/__manifest__.py
  ddmrp_history/models/ddmrp_history.py
  ddmrp_history/security/security.xml
  ddmrp_history/views/ddmrp_history_view.xml
Labels: bot is merging ⏳, Pending to fw/back port

#449 [15.0][IMP] ddmrp_history: add multicompany rules
  ddmrp_history/__manifest__.py
  ddmrp_history/models/ddmrp_history.py
  ddmrp_history/security/security.xml
  ddmrp_history/views/ddmrp_history_view.xml
Labels: bot is merging ⏳

#450 [14.0][IMP] ddmrp_history: add multicompany rules
  ddmrp_history/__manifest__.py
  ddmrp_history/models/ddmrp_history.py
  ddmrp_history/security/security.xml
  ddmrp_history/views/ddmrp_history_view.xml
Labels: bot is merging ⏳

#451 [16.0][IMP] ddmrp_report_part_flow_index: add multi-company restrictions
  ddmrp_report_part_flow_index/__manifest__.py
  ddmrp_report_part_flow_index/reports/report_ddmrp_part_plan_flow_index.py
  ddmrp_report_part_flow_index/reports/report_ddmrp_part_plan_flow_index_views.xml
  ddmrp_report_part_flow_index/security/report_ddmrp_part_plan_flow_index_security.xml
Labels: bot is merging ⏳, Pending to fw/back port

#452 [15.0][MIG] ddmrp_report_part_flow_index
  ddmrp_report_part_flow_index/README.rst
  ddmrp_report_part_flow_index/__init__.py
  ddmrp_report_part_flow_index/__manifest__.py
  ddmrp_report_part_flow_index/i18n/ddmrp_report_part_flow_index.pot
  ddmrp_report_part_flow_index/i18n/it.po
  ddmrp_report_part_flow_index/models/__init__.py
  ddmrp_report_part_flow_index/models/ddmrp_flow_index_group.py
  ddmrp_report_part_flow_index/models/stock_buffer.py
  ddmrp_report_part_flow_index/readme/CONFIGURE.rst
  ddmrp_report_part_flow_index/readme/CONTRIBUTORS.rst
  ddmrp_report_part_flow_index/readme/DESCRIPTION.rst
  ddmrp_report_part_flow_index/readme/HISTORY.rst
  ddmrp_report_part_flow_index/readme/ROADMAP.rst
  ddmrp_report_part_flow_index/readme/USAGE.rst
  ddmrp_report_part_flow_index/reports/__init__.py
  ddmrp_report_part_flow_index/reports/report_ddmrp_part_plan_flow_index.py
  ddmrp_report_part_flow_index/reports/report_ddmrp_part_plan_flow_index_views.xml
  ddmrp_report_part_flow_index/security/ir.model.access.csv
  ddmrp_report_part_flow_index/security/report_ddmrp_part_plan_flow_index_security.xml
  ddmrp_report_part_flow_index/static/description/icon.png
  ddmrp_report_part_flow_index/static/description/index.html
  ddmrp_report_part_flow_index/views/ddmrp_flow_index_group_views.xml
  ddmrp_report_part_flow_index/views/stock_buffer_view.xml
  setup/ddmrp_report_part_flow_index/odoo/addons/ddmrp_report_part_flow_index
  setup/ddmrp_report_part_flow_index/setup.py
Labels: bot is merging ⏳

#453 [14.0][MIG] ddmrp_report_part_flow_index
  ddmrp_report_part_flow_index/README.rst
  ddmrp_report_part_flow_index/__init__.py
  ddmrp_report_part_flow_index/__manifest__.py
  ddmrp_report_part_flow_index/i18n/ddmrp_report_part_flow_index.pot
  ddmrp_report_part_flow_index/i18n/it.po
  ddmrp_report_part_flow_index/models/__init__.py
  ddmrp_report_part_flow_index/models/ddmrp_flow_index_group.py
  ddmrp_report_part_flow_index/models/stock_buffer.py
  ddmrp_report_part_flow_index/readme/CONFIGURE.rst
  ddmrp_report_part_flow_index/readme/CONTRIBUTORS.rst
  ddmrp_report_part_flow_index/readme/DESCRIPTION.rst
  ddmrp_report_part_flow_index/readme/HISTORY.rst
  ddmrp_report_part_flow_index/readme/ROADMAP.rst
  ddmrp_report_part_flow_index/readme/USAGE.rst
  ddmrp_report_part_flow_index/reports/__init__.py
  ddmrp_report_part_flow_index/reports/report_ddmrp_part_plan_flow_index.py
  ddmrp_report_part_flow_index/reports/report_ddmrp_part_plan_flow_index_views.xml
  ddmrp_report_part_flow_index/security/ir.model.access.csv
  ddmrp_report_part_flow_index/security/report_ddmrp_part_plan_flow_index_security.xml
  ddmrp_report_part_flow_index/static/description/icon.png
  ddmrp_report_part_flow_index/static/description/index.html
  ddmrp_report_part_flow_index/views/ddmrp_flow_index_group_views.xml
  ddmrp_report_part_flow_index/views/stock_buffer_view.xml
  setup/ddmrp_report_part_flow_index/odoo/addons/ddmrp_report_part_flow_index
  setup/ddmrp_report_part_flow_index/setup.py
Labels: bot is merging ⏳

#442 [14.0][IMP] ddmrp: Add customized Stock Moves view
  ddmrp/models/stock_buffer.py
  ddmrp/models/stock_move.py
  ddmrp/views/stock_buffer_view.xml
  ddmrp/views/stock_move_views.xml
Labels: bot is merging ⏳

#454 [15.0][IMP] ddmrp: Add customized Stock Moves view
  ddmrp/models/stock_buffer.py
  ddmrp/models/stock_move.py
  ddmrp/views/stock_buffer_view.xml
  ddmrp/views/stock_move_views.xml
Labels: bot is merging ⏳

#446 [16.0][IMP] ddmrp: Add customized Stock Moves view
  ddmrp/models/stock_buffer.py
  ddmrp/models/stock_move.py
  ddmrp/views/stock_buffer_view.xml
  ddmrp/views/stock_move_views.xml
Labels: bot is merging ⏳

#455 [16.0][IMP] ddmrp: Make fields invisible or readonly if user not in group
  ddmrp/wizards/make_procurement_buffer.py
  ddmrp/wizards/make_procurement_buffer_view.xml
Labels: bot is merging ⏳

#456 [16.0][IMP] ddmrp_report_part_flow_index: add access rights to buffer mantainers
  ddmrp_report_part_flow_index/models/ddmrp_flow_index_group.py
  ddmrp_report_part_flow_index/reports/report_ddmrp_part_plan_flow_index.py
  ddmrp_report_part_flow_index/security/ir.model.access.csv
Labels: bot is merging ⏳

#457 [16.0][FIX] ddmrp: when procuring without permissions to change qty an error raises
  ddmrp/wizards/make_procurement_buffer_view.xml
Labels: needs review, bot is merging ⏳

#459 [14.0][IMP] ddmrp_report_part_flow_index: add access rights to buffer mantainers
  ddmrp_report_part_flow_index/models/ddmrp_flow_index_group.py
  ddmrp_report_part_flow_index/reports/report_ddmrp_part_plan_flow_index.py
  ddmrp_report_part_flow_index/security/ir.model.access.csv
Labels: bot is merging ⏳

#458 [15.0][IMP] ddmrp_report_part_flow_index: add access rights to buffer mantainers
  ddmrp_report_part_flow_index/models/ddmrp_flow_index_group.py
  ddmrp_report_part_flow_index/reports/report_ddmrp_part_plan_flow_index.py
  ddmrp_report_part_flow_index/security/ir.model.access.csv
Labels: bot is merging ⏳
