Repository OCA/ddmrp, pull requests merged in 2024-04, with the labels that each got.

#428 [15.0][FIX] ddmrp_adjustment: do not overload original docstring of _calc_adu
  ddmrp_adjustment/models/stock_buffer.py
Labels: bot is merging ⏳

#430 [16.0][FIX] ddmrp_adjustment: do not overload original docstring of _calc_adu
  ddmrp_adjustment/models/stock_buffer.py
Labels: bot is merging ⏳

#429 [13.0][FIX] ddmrp_adjustment: do not overload original docstring of _calc_adu
  ddmrp_adjustment/models/stock_buffer.py
Labels: bot is merging ⏳

#431 [16.0] [MIG] ddmrp_report_part_flow_index
  ddmrp_report_part_flow_index/README.rst
  ddmrp_report_part_flow_index/__init__.py
  ddmrp_report_part_flow_index/__manifest__.py
  ddmrp_report_part_flow_index/i18n/ddmrp_report_part_flow_index.pot
  ddmrp_report_part_flow_index/models/__init__.py
  ddmrp_report_part_flow_index/models/ddmrp_flow_index_group.py
  ddmrp_report_part_flow_index/models/stock_buffer.py
  ddmrp_report_part_flow_index/readme/CONFIGURE.rst
  ddmrp_report_part_flow_index/readme/CONTRIBUTORS.rst
  ddmrp_report_part_flow_index/readme/DESCRIPTION.rst
  ddmrp_report_part_flow_index/readme/HISTORY.rst
  ddmrp_report_part_flow_index/readme/ROADMAP.rst
  ddmrp_report_part_flow_index/readme/USAGE.rst
  ddmrp_report_part_flow_index/reports/__init__.py
  ddmrp_report_part_flow_index/reports/report_ddmrp_part_plan_flow_index.py
  ddmrp_report_part_flow_index/reports/report_ddmrp_part_plan_flow_index_views.xml
  ddmrp_report_part_flow_index/security/ir.model.access.csv
  ddmrp_report_part_flow_index/static/description/icon.png
  ddmrp_report_part_flow_index/static/description/index.html
  ddmrp_report_part_flow_index/views/ddmrp_flow_index_group_views.xml
  ddmrp_report_part_flow_index/views/stock_buffer_view.xml
  setup/ddmrp_report_part_flow_index/odoo/addons/ddmrp_report_part_flow_index
  setup/ddmrp_report_part_flow_index/setup.py
Labels: needs fixing, bot is merging ⏳

#432 [14.0][FIX] ddmrp: filter explicitly by type to get manufacture BoM
  ddmrp/models/stock_buffer.py
Labels: bot is merging ⏳, Pending to fw/back port

#433 [16.0][FW][FIX] ddmrp: filter explicitly by type to get manufacture BoM
  ddmrp/models/stock_buffer.py
Labels: bot is merging ⏳

#434 [15.0][FW][FIX] ddmrp: filter explicitly by type to get manufacture BoM
  ddmrp/models/stock_buffer.py
Labels: bot is merging ⏳

#436 [14.0][IMP] ddmrp_chatter: add tracking for active field
  ddmrp_chatter/models/stock_buffer.py
Labels: bot is merging ⏳

#437 [15.0][FW][IMP] ddmrp_chatter: add tracking for active field
  ddmrp_chatter/models/stock_buffer.py
Labels: bot is merging ⏳

#438 [16.0][FW][IMP] ddmrp_chatter: add tracking for active field
  ddmrp_chatter/models/stock_buffer.py
Labels: bot is merging ⏳

#435 [16.0][IMP] ddmrp_report_part_flow_index: change the way flow index is assigned to buffers
  ddmrp_report_part_flow_index/models/ddmrp_flow_index_group.py
  ddmrp_report_part_flow_index/models/stock_buffer.py
  ddmrp_report_part_flow_index/views/ddmrp_flow_index_group_views.xml
  ddmrp_report_part_flow_index/views/stock_buffer_view.xml
Labels: bot is merging ⏳
