Repository OCA/ddmrp, pull requests merged in 2024-02, with the labels that each got.

#383 [14.0][IMP] ddmrp*: Use ddmrp security groups
  ddmrp_adjustment/security/ir.model.access.csv
  ddmrp_history/security/ir.model.access.csv
  ddmrp_product_replace/security/ir.model.access.csv
  ddmrp_warning/security/ir.model.access.csv
Labels: Pending to fw/back port

#385 [15.0][PORT] ddmrp*: Use ddmrp security groups
  ddmrp_adjustment/security/ir.model.access.csv
  ddmrp_history/security/ir.model.access.csv
  ddmrp_product_replace/security/ir.model.access.csv
  ddmrp_warning/security/ir.model.access.csv
Labels: bot is merging ⏳

#386 [16.0][PORT] ddmrp*: Use ddmrp security groups
  ddmrp_adjustment/security/ir.model.access.csv
  ddmrp_history/security/ir.model.access.csv
  ddmrp_product_replace/security/ir.model.access.csv
  ddmrp_warning/security/ir.model.access.csv
Labels: bot is merging ⏳

#384 [13.0][BACKPORT] ddmrp*: Use ddmrp security groups
  ddmrp_adjustment/security/ir.model.access.csv
  ddmrp_history/security/ir.model.access.csv
  ddmrp_product_replace/security/ir.model.access.csv
  ddmrp_warning/security/ir.model.access.csv
Labels: bot is merging ⏳

#387 [16.0][IMP] ddmrp: small UX improvements
  ddmrp/models/stock_buffer.py
  ddmrp/views/product_adu_calculation_method_view.xml
  ddmrp/views/stock_buffer_view.xml
  ddmrp_adjustment/views/stock_buffer_view.xml
Labels: approved, bot is merging ⏳

#389 [16.0][FIX] ddmrp: user without access to manufacturing app to update buffers
  ddmrp/security/ir.model.access.csv
Labels: approved, bot is merging ⏳

#373 [14.0][FIX] ddmrp: Auto-calculate warehouse when duplicating buffers
  ddmrp/wizards/ddmrp_duplicate_buffer.py
Labels: bot is merging ⏳

#391 [16.0][FIX] ddmrp: Auto-calculate warehouse when duplicating buffers
  ddmrp/wizards/ddmrp_duplicate_buffer.py
Labels: bot is merging ⏳

#390 [15.0][FIX] ddmrp: Auto-calculate warehouse when duplicating buffers
  ddmrp/models/stock_buffer.py
  ddmrp/wizards/ddmrp_duplicate_buffer.py
Labels: bot is merging ⏳

#392 [13.0][FIX] ddmrp: Auto-calculate warehouse when duplicating buffers
  ddmrp/wizards/ddmrp_duplicate_buffer.py
Labels: bot is merging ⏳

#393 [15.0][FIX] ddmrp: user without access to manufacturing app to update buffers
  ddmrp/security/ir.model.access.csv
Labels: bot is merging ⏳

#394 [14.0][FIX] ddmrp: user without access to manufacturing app to update buffers
  ddmrp/security/ir.model.access.csv
Labels: bot is merging ⏳

#395 [13.0][FIX] ddmrp: user without access to manufacturing app to update buffers
  ddmrp/security/ir.model.access.csv
Labels: bot is merging ⏳

#398 [14.0] ddmrp: fix duplicating buffer access right
  ddmrp/security/ir.model.access.csv
Labels: bot is merging ⏳

#400 [16.0] ddmrp: fix duplicating buffer access right
  ddmrp/security/ir.model.access.csv
Labels: bot is merging ⏳

#399 [15.0] ddmrp: fix duplicating buffer access right
  ddmrp/security/ir.model.access.csv
Labels: bot is merging ⏳

#397 [16.0] [IMP] ddmrp_chatter: add activities in tree view
  ddmrp_chatter/views/ddmrp_buffer_view.xml
Labels: approved, bot is merging ⏳

#369 [14.0][REF] ddmrp: Compute dlt depending on buffer location
  ddmrp/__manifest__.py
  ddmrp/demo/mrp_bom_demo.xml
  ddmrp/models/mrp_bom.py
  ddmrp/models/stock_buffer.py
  ddmrp/report/mrp_report_bom_structure.xml
  ddmrp/security/ir.model.access.csv
  ddmrp/static/description/index.html
  ddmrp/static/src/js/mrp_bom_report.js
  ddmrp/tests/test_ddmrp.py
  ddmrp/views/ddmrp_assets_backend.xml
  ddmrp/views/mrp_bom_view.xml
  ddmrp/views/stock_buffer_view.xml
  ddmrp/wizards/__init__.py
  ddmrp/wizards/mrp_bom_change_location.py
  ddmrp/wizards/mrp_bom_change_location.xml
Labels: bot is merging ⏳, Pending to fw/back port

#406 [14.0][FIX] ddmrp: Bom Line search buffer domain
  ddmrp/models/mrp_bom.py
Labels: bot is merging ⏳

#407 [15.0][PORT] ddmrp: Bom Line search buffer domain
  ddmrp/models/mrp_bom.py
Labels: bot is merging ⏳

#404 [13.0][BACKPORT] ddmrp: Compute dlt depending on buffer location
  ddmrp/__manifest__.py
  ddmrp/demo/mrp_bom_demo.xml
  ddmrp/models/mrp_bom.py
  ddmrp/models/stock_buffer.py
  ddmrp/report/mrp_report_bom_structure.xml
  ddmrp/static/description/index.html
  ddmrp/static/src/js/mrp_bom_report.js
  ddmrp/tests/test_ddmrp.py
  ddmrp/views/ddmrp_assets_backend.xml
  ddmrp/views/mrp_bom_view.xml
  ddmrp/views/stock_buffer_view.xml
  ddmrp/wizards/__init__.py
  ddmrp/wizards/mrp_bom_change_location.py
  ddmrp/wizards/mrp_bom_change_location.xml
Labels: bot is merging ⏳

#403 [16.0][MIG] ddmrp_sale + [ADD] ddmrp_exclude_moves_adu_calc_sales
  ddmrp_exclude_moves_adu_calc_sales/README.rst
  ddmrp_exclude_moves_adu_calc_sales/__init__.py
  ddmrp_exclude_moves_adu_calc_sales/__manifest__.py
  ddmrp_exclude_moves_adu_calc_sales/models/__init__.py
  ddmrp_exclude_moves_adu_calc_sales/models/sale_order_line.py
  ddmrp_exclude_moves_adu_calc_sales/readme/CONTRIBUTORS.rst
  ddmrp_exclude_moves_adu_calc_sales/readme/DESCRIPTION.rst
  ddmrp_exclude_moves_adu_calc_sales/static/description/icon.png
  ddmrp_exclude_moves_adu_calc_sales/static/description/index.html
  ddmrp_exclude_moves_adu_calc_sales/views/sale_order_view.xml
  ddmrp_sale/README.rst
  ddmrp_sale/__init__.py
  ddmrp_sale/__manifest__.py
  ddmrp_sale/i18n/ddmrp_sale.pot
  ddmrp_sale/i18n/it.po
  ddmrp_sale/models/__init__.py
  ddmrp_sale/models/stock_buffer.py
  ddmrp_sale/readme/CONTRIBUTORS.rst
  ddmrp_sale/readme/DESCRIPTION.rst
  ddmrp_sale/readme/HISTORY.rst
  ddmrp_sale/static/description/icon.png
  ddmrp_sale/static/description/index.html
  ddmrp_sale/tests/__init__.py
  ddmrp_sale/tests/test_ddmrp_sale.py
  ddmrp_sale/views/stock_buffer_view.xml
  setup/ddmrp_exclude_moves_adu_calc_sales/odoo/addons/ddmrp_exclude_moves_adu_calc_sales
  setup/ddmrp_exclude_moves_adu_calc_sales/setup.py
  setup/ddmrp_sale/odoo/addons/ddmrp_sale
  setup/ddmrp_sale/setup.py
Labels: bot is merging ⏳

#408 [16.0][PORT] ddmrp: Compute dlt depending on buffer location
  ddmrp/README.rst
  ddmrp/__manifest__.py
  ddmrp/demo/mrp_bom_demo.xml
  ddmrp/models/mrp_bom.py
  ddmrp/models/stock_buffer.py
  ddmrp/security/ir.model.access.csv
  ddmrp/static/description/index.html
  ddmrp/static/src/components/bom_overview/mrp_bom_overview.esm.js
  ddmrp/tests/common.py
  ddmrp/tests/test_ddmrp.py
  ddmrp/views/mrp_bom_view.xml
  ddmrp/views/stock_buffer_view.xml
  ddmrp/wizards/__init__.py
  ddmrp/wizards/mrp_bom_change_location.py
  ddmrp/wizards/mrp_bom_change_location.xml
Labels: bot is merging ⏳

#410 [16.0][REF] ddmrp_exclude_moves_adu_calc: change stock manager permision to buffer maintainer
  ddmrp_exclude_moves_adu_calc/models/stock_move.py
  ddmrp_exclude_moves_adu_calc/tests/test_ddmrp.py
Labels: bot is merging ⏳, Pending to fw/back port

#409 [16.0][IMP] ddmrp_exclude_moves_adu_calc_sales
  ddmrp_exclude_moves_adu_calc_sales/README.rst
  ddmrp_exclude_moves_adu_calc_sales/__manifest__.py
  ddmrp_exclude_moves_adu_calc_sales/models/__init__.py
  ddmrp_exclude_moves_adu_calc_sales/models/stock_move.py
  ddmrp_exclude_moves_adu_calc_sales/static/description/index.html
  ddmrp_exclude_moves_adu_calc_sales/tests/__init__.py
  ddmrp_exclude_moves_adu_calc_sales/tests/test_ddmrp_exclude_moves_adu_calc_sales.py
Labels: bot is merging ⏳

#413 [13.0][REF] ddmrp_exclude_moves_adu_calc: change stock manager permision to buffer maintainer
  ddmrp_exclude_moves_adu_calc/models/stock_move.py
  ddmrp_exclude_moves_adu_calc/tests/test_ddmrp.py
Labels: bot is merging ⏳

#412 [14.0][REF] ddmrp_exclude_moves_adu_calc: change stock manager permision to buffer maintainer
  ddmrp_exclude_moves_adu_calc/models/stock_move.py
  ddmrp_exclude_moves_adu_calc/tests/test_ddmrp.py
Labels: bot is merging ⏳

#411 [15.0][REF] ddmrp_exclude_moves_adu_calc: change stock manager permision to buffer maintainer
  ddmrp_exclude_moves_adu_calc/models/stock_move.py
  ddmrp_exclude_moves_adu_calc/tests/test_ddmrp.py
Labels: bot is merging ⏳
